# Generated by Django 5.2.6 on 2025-10-01 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('income', 'Income Statement'), ('balance', 'Balance Sheet')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('owner', 'year')},
        ),
    ]
