# Generated by Django 5.2.6 on 2025-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
