# Generated by Django 5.2.6 on 2025-10-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_document_analyzed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('income', 'Income Statement'), ('balance', 'Balance Sheet'), ('rozvaha', 'Rozvaha'), ('vysledovka', 'Výsledovka'), ('cashflow', 'Cash Flow'), ('other', 'Ostatní dokumenty')], max_length=20),
        ),
    ]
