# Generated by Django 5.2.6 on 2025-12-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_single_statement_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='local_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingest.document'),
        ),
    ]
