# Generated by Django 5.2.1 on 2025-12-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_financialstatement_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rag_error_message',
            field=models.TextField(blank=True, help_text='Error details if RAG processing failed'),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_processing_mode',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('batch', 'Batch (nightly)'), ('manual', 'Manual only')], default='immediate', help_text='When to process this document for RAG', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_retry_count',
            field=models.IntegerField(default=0, help_text='Number of retry attempts'),
        ),
        migrations.AddField(
            model_name='document',
            name='rag_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of RAG processing (chunking + embeddings)', max_length=20),
        ),
    ]
