# Generated by Django 5.2.6 on 2025-10-01 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Název firmy')),
                ('ico', models.CharField(blank=True, max_length=20, null=True, verbose_name='IČO')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontaktní osoba')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Webové stránky')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Odvětví působnosti')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Počet zaměstnanců')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.coach')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('company', 'Firma'), ('coach', 'Kouč')], default='company', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
