# Generated by Django 5.2.6 on 2025-10-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Město'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Právní forma'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PSČ'),
        ),
    ]
