# Generated by Django 5.2.6 on 2025-10-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_address_companyprofile_city_and_more'),
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachClientNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_notes', to='accounts.companyprofile')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='coaching.coach')),
            ],
            options={
                'verbose_name': 'Poznámka kouče',
                'verbose_name_plural': 'Poznámky kouče',
                'unique_together': {('coach', 'client')},
            },
        ),
    ]
