# Generated by Django 5.2.6 on 2025-10-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suropen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openanswer",
            options={"ordering": ["-created_at"]},
        ),
    ]
